substitutions = {
"witness": "dude I know",
"witnesses": "theese dudes I know",
"rebuild": "avenge",
"space": "spaaaace",
"smartphone": "Pokédex",
"electric": "atomic",
"car": "cat",
"cars": "cats",
"election": "eating contest",
"debate": "dance-off",
"poll": "physic reading",
"candidate": "airbender",
"drone": "dog",
"successfully": "suddenly",
"expands": "physically expands",
"first-degree": "friggin' auful",
"second-degree": "friggin' auful",
"third-degree": "friggin' auful",
"global": "spherical",
"candidate": "airbender",
"year": "minutes",
"minutes": "years",
"horsepower": "tons of horsemeat",
"gaffe": "magic spell",
"ancient": "haunted",
"star-studded": "blood-soaked",
"surprising": "surprising (but not to me)",
"surprisingly": "surprisingly (but not to me)",
"tension": "sexual tension",
"email": "poem",
"tweet": "poem",
"latest": "final",
"disrupt": "destroy",
"meeting": "ménage à trois",
"scientist": "Chaning Tatum and his friends",
"scientists": "Chaning Tatum and his friends",
}
