substitutions = {
"witness": "dude I know",
"witnesses": "theese dudes I know",
"rebuild": "avenge",
"space": "spaaaace",
"smartphone": "Pokédex",
"electric": "atomic",
"car": "cat",
"cars": "cats",
"election": "eating contest",
"debate": "dance-off",
"poll": "physic reading",
"candidate": "airbender",
"drone": "dog",
"successfully": "suddenly",
"expands": "physically expands",
"first-degree": "friggin' auful",
"second-degree": "friggin' auful",
"third-degree": "friggin' auful",
"global": "spherical",
"candidate": "airbender",
"year": "minutes",
"minutes": "years",
"horsepower": "tons of horsemeat",
"gaffe": "magic spell",
"ancient": "haunted",
"star-studded": "blood-soaked",
"surprising": "surprising (but not to me)",
"surprisingly": "surprisingly (but not to me)",
"tension": "sexual tension",
"email": "poem",
"tweet": "poem",
"latest": "final",
"disrupt": "destroy",
"meeting": "ménage à trois",
"scientist": "Chaning Tatum and his friends",
"scientists": "Chaning Tatum and his friends",
"dear friend": "fiendemy",
"says": "lip-synchs",
"say": "lip-synch",
"said": "lip-synched",
"new study": "tumbler post",
"google glass": "Virtual Boy",
"congressional leaders": "river spirits",
"homeland security": "The Voice UK",
"could not be reached for comments": "is guilty and everyone knows it",
"self driving": "uncontrollably swerving",
"vows to": "probably won't",
"at large": "very large",
"said": "burped",
"said": "burped",
"said": "burped",
"said": "burped",
"first degree": "friggin' auful",
"second degree": "friggin' auful",
"an unknown number": "like hundreds",
"front runner": "blade runner",
"no indication": "lots of signs",
"urgerd restraint by": "drunkenly egged on",
"remains to be seen": "will never be known",
"silver bullet": "way to kill werewolves",
"subway system": "tunnels I found",
"war of words": "interplanetary war",
"cautiously optimistic": "delusional",
"doctor who": "The Big Bank Theory",
"win votes": "find Pokémon",
"behind the headlines": "beyond the grave",
"facebook ceo": "this guy",
"you won't believe": "I'm really sad about",
"trump": "Rick Astley",
"sexual": "a bit awkard",
"county": "piece of land",
"misconduct": "being a piece of shit",
"korea": "Narnia"
}
